REM Use full pathnames to files as appropriate
REM e.g TiledTMXToEnchant c:\project\content\map_level_one.tmx enchant.txt game.js
REM Running Tool
TiledTMXToEnchant "C:\Users\SocksUp\SkyDrive\Modules\COMP-06037-Digital Game Design\Student-COMP-06037\Labs\WIP\VisualStudio2013Project\TiledTMXToEnchant\TiledTMXToEnchant\map.tmx" "C:\project\myproject\enchant.txt" "C:\Users\SocksUp\SkyDrive\Devtools\enchant.js-builds-0.8.0\examples\expert\rpg_test\game.js"
REM Tool Complete